version: 2
updates:
  - package-ecosystem: "pip"  # Specifies the package ecosystem as Python's pip
    directory: "/"             # Location of the requirements.txt file
    schedule:
      interval: "weekly"       # Set to check for updates weekly
    open-pull-requests-limit: 5 # Limit the number of open pull requests
    ignore:                    # Specify dependencies to ignore
      - dependency-name: "arcpy"  # Ignore arcpy
        versions: []              # Ignore all versions
      - dependency-name: "netCDF4" # Ignore netCDF4
        versions: []              # Ignore all versions
